### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [Oleksii-Ivanichok/logical-expression-parser-rust#1]
Student: Іванічок Олексій

Для прохідного:
:heavy_check_mark:  ! CLI: 
:heavy_check_mark:  ! Brief Description:
:heavy_check_mark:  ! Project Name:
:heavy_check_mark:  ! Grammar Rules: допустимо я прийму
:heavy_check_mark:  ! Unit Tests:
:heavy_check_mark:  ! Core Files:

Для мааксимального:
:x:  File System: я щось не бачу також і запис у файл
:heavy_check_mark:  Test Coverage: 
:x:  Error Handling: я бачу unreachable!() у lib. Впевнений, що це хороша ідея? Також у тестах використовуй `anyhow::Result<()>`
:heavy_check_mark:  cargo fmt: 
cargo clippy: TODO
:heavy_check_mark:  makefile:
:x: Completeness: після всіх змін  
:heavy_check_mark:  Including a diagram or grammar in the Readme.md:
:x:  Documentation:  немає
:x:  Publishing: після змін

:heavy_check_mark:  Курсова може бути зарахована
Бал: 12/25

**Comment by NYBACHOK** [comment]
Привіт. Ти пушив зміни, бо я не бачу, щоби щось оновлювалося з понеділка

**Comment by NYBACHOK** [comment]
Привіт. Напиши чи погоджуєшся з баламив

**Comment by Oleksii-Ivanichok** [comment]
походжуюся, а чому 12 з 25, якщо курсова на 40 балів(я вчасно здав)?

**Comment by Oleksii-Ivanichok** [comment]
я правильно розумію що за курс можна набрати 100 балів, якщо за курсову не максимальний?

**Comment by NYBACHOK** [comment]
На рахунок курсової. Максимальний бал 25 і у файлі, який інші ментори мали використовувати для оцінювання прописано саме так.  
Перший дедлайн був минулої середи за нього просто мають зменшувати бали. Цієї середи фінальний дедлайн
Наскільки мені відомо за курс максимально 100 балів, але у вас була можливість отримати 140+ балів, якщо виконувати всі завдання. Курсова обов'язкова до виконання і мінімально за неї 5 балів

**Comment by Oleksii-Ivanichok** [comment]
> На рахунок курсової. Максимальний бал 25 і у файлі, який інші ментори мали використовувати для оцінювання прописано саме так. Перший дедлайн був минулої середи за нього просто мають зменшувати бали. Цієї середи фінальний дедлайн Наскільки мені відомо за курс максимально 100 балів, але у вас була можливість отримати 140+ балів, якщо виконувати всі завдання. Курсова обов'язкова до виконання і мінімально за неї 5 балів

я згадав 40 балів це в сумі, а за останнє завдання - 25. Дякую
